name: My-first-workflow
on: []
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: hello
        run: echo "Hello, my first workflow"
