name: My-first-workflow
on: 
  push:
    paths:
      - tests/**
      - flaskr/**
jobs:
  build:
    if: github.ref!='remote/release'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: hello
        run: echo "Hello, my first workflow"
      - name: python env
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: install dependencies
        run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - name: find project
        run: echo $GITHUB_WORKSPACE
      - name: linting
        continue-on-error: true
        if: github.ref=='remote/main'
        run: flake8 . --count
      - name: coverage test
        if: github.ref=='remote/main'
        run: coverage run -m pytest
      - run: coverage report
        if: github.ref=='remote/main'
        
